import type { Trade } from '@/lib/types';

export const mockTrades: Trade[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 1 * 60000),
    pair: 'EUR/USD',
    direction: 'buy',
    stake: 10,
    outcome: 'win',
    profit: 8.7,
    aiPrediction: 0.88,
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 5 * 60000),
    pair: 'GBP/JPY',
    direction: 'sell',
    stake: 10,
    outcome: 'loss',
    profit: -10,
    aiPrediction: 0.76,
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 12 * 60000),
    pair: 'AUD/CAD',
    direction: 'buy',
    stake: 15,
    outcome: 'win',
    profit: 12.5,
    aiPrediction: 0.92,
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 20 * 60000),
    pair: 'EUR/USD',
    direction: 'sell',
    stake: 10,
    outcome: 'win',
    profit: 8.7,
    aiPrediction: 0.81,
  },
    {
    id: '5',
    timestamp: new Date(Date.now() - 30 * 60000),
    pair: 'USD/CHF',
    direction: 'buy',
    stake: 20,
    outcome: 'loss',
    profit: -20,
    aiPrediction: 0.65,
  },
];
